from twitter.main import UseTwitter

user1 = UseTwitter(headless=False)
user1.set_user(user_id='OnceHuman_')
tweet_text, tweet_image, tweet_video, share_link = user1.get_post_data()
print('tweet text : ', tweet_text)
print('tweet image : ', tweet_image)
print('tweet video : ', tweet_video)
print('share link : ', share_link)
banner, pfp, name, uid, description, link, joined_date = user1.get_profile()
print('banner : ', banner)
print('pfp : ', pfp)
print('name : ', name)
print('uid : ', uid)
print('description : ', description)
print('link : ', link)
print('joined_date : ', joined_date)
user1.set_user(user_id='MrBeast')
tweet_text, tweet_image, tweet_video, share_link = user1.get_post_data()
print('tweet text : ', tweet_text)
print('tweet image : ', tweet_image)
print('tweet video : ', tweet_video)
print('share link : ', share_link)
banner, pfp, name, uid, description, link, joined_date = user1.get_profile()
print('banner : ', banner)
print('pfp : ', pfp)
print('name : ', name)
print('uid : ', uid)
print('description : ', description)
print('link : ', link)
print('joined_date : ', joined_date)

